PREFIX mission: <http://imce.jpl.nasa.gov/foundation/mission#>

ASK {
  BIND(<http://studioj.us/mass-props-oml/WP.4/IT/IT.C.1.1_out#IT.C.1.1_out> as ?in_item)
  BIND(<http://studioj.us/mass-props-oml/WP.4/IT/IT.C.1.2_out#IT.C.1.2_out> as ?out_item)

  #
  # direct path through parent component
  #

  ?in_item ^mission:transfersIn/^mission:presents/mission:presents/mission:transfersOut ?out_item .

  #
  # indirect path through implementing components
  #

  ?in_item
    ^mission:transfersIn/^mission:presents
    /
    (mission:presents/mission:transfersOut/mission:traverses/^mission:traverses/^mission:transfersIn/^mission:presents)+
    /
    mission:presents/mission:transfersOut
  ?out_item
}
