# finds importing descriptions whose imported descriptions do not grant rights to the
# creator of the importing description
# rights are explicit when the rights of the imported match the creator of the importing
# rights are implicit when not explicit and right of the imported as a regex match the creator of the importing

PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX oml: <http://opencaesar.io/oml#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX project: <http://imce.jpl.nasa.gov/foundation/project#>
SELECT ?creator ?importing ?imported
WHERE {
    ?importing owl:imports ?imported ;
        oml:type oml:Description ;
        dc:creator ?creator .
    ?imported oml:type oml:Description .
BIND(EXISTS { ?imported dc:rights ?creator } as ?has_explicit_rights)
BIND(!?has_explicit_rights && EXISTS { ?imported dc:rights ?holder FILTER(REGEX(STR(?creator), STR(?holder))) } as ?has_implicit_rights)
FILTER(!?has_explicit_rights && !?has_implicit_rights)
}
ORDER BY ?imported ?importing