# finds importing descriptions whose imported descriptions do not grant rights to the
# creator of the importing description

PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX oml: <http://opencaesar.io/oml#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX project: <http://imce.jpl.nasa.gov/foundation/project#>
SELECT ?creator ?importing ?imported
WHERE {
    ?importing owl:imports ?imported ;
        oml:type oml:Description ;
        dc:creator ?creator .
    ?imported oml:type oml:Description .
    BIND(EXISTS { ?imported dc:creator ?creator } as ?has_creator_rights)
    BIND(EXISTS { ?imported dc:rights ?creator } as ?has_explicit_rights)
    BIND(NOT EXISTS {
        ?imported dc:rights ?holder .
        ?auth a project:Authority
        FILTER(IRI(STR(?holder)) = ?auth)
        }  as ?has_implicit_rights)
    FILTER(!(?has_creator_rights || ?has_explicit_rights || ?has_implicit_rights))
}
ORDER BY ?imported
